name: Create Release

on: push

env:
  file_name: ${{ github.event.repository.name }}-${{ github.ref_name }}.kwinscript

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          zip -r ${{ env.file_name }} LICENSE README.md
          cd package
          zip -r ../${{ env.file_name }} *
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.file_name }}
